# Configuração do Dependabot para manter dependências atualizadas

version: 2
updates:
  # Monitorar dependências do backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "seu-usuario"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Monitorar dependências do frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "seu-usuario"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Monitorar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "seu-usuario"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
